openapi: 3.0.0
info:
  title: The library 4 System 3.0
  description:
    This is a library management system Server based on the OpenAPI 3.0 specification.
  version: 1.0.0

servers:
  - url: https:/localhost:8080/api/v1


paths:
  /categories:
    get:
      tags:
      - Category
      summary: get all categories
      description: Category
      operationId: get_All_Categories
      responses:
        "200":
          description: Categories successfully retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categories"
        default:
          description: Errors
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a new category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the category
                description:
                  type: string
                  description: A description of the category
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    description: The ID of the newly created category
                  name:
                    type: string
                    description: The name of the category
                  description:
                    type: string
                    description: A description of the category
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error




  /categories/{categoryID}:
    put:
      summary: update an existing category
      parameters:
      - in: path
        name: categoryID
        required: true
        description: ID of the category to be updated
        schema:
          type: integer
          format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: the update name of the category
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    description: id of the category to be updated
                  name:
                    type: string
                    description: updated name of the category
                  description:
                    type: string
                    description: updated description of category
        "404":
          description: not found
        "500":
          description: server error





    delete:
      tags:
        - Category
      summary: delete one category
      description: delete a category
      parameters:
       -  name: categoryID
          in: path
          description: an integer that identify a category
          required: true
          schema:
            type: integer
            example: 1
      responses:
        "204":
          description: no content
        "404":
          description: not found


    get:
      parameters:
        - name: categoryID
          in: path
          description: an integer to identify the category
          required: true
          schema:
            type: integer
            example: 1
      tags:
        - Category
      summary: get a single category by its ID
      description: one Category
      operationId: get_one_category

      responses:
        "200":
          description: Successful response with one book
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        default:
          description: Errors
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
         description: category not found
         content:
          application/json:
            schema:
              type: object
              properties:
                error:
                  type: string
                  description: error message
            example:
              error: category not found
components:
  schemas:
    Category:
      type: object
      required:
        - ID
        - name
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Fiction"
    Categories:
      type: array
      items:
        $ref: '#/components/schemas/Category'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string


